const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const BookSchema = new Schema({
    "tplMsg":{
        "isBack":{type:Boolean,default:false},
        "isNew":{type:Boolean,default:true},
        "showSealLine":{type:Boolean,default:false},
        "testId":Schema.Types.ObjectId,
        "title":{type:String,default:"2018年普通高等学校招生全国统一考试"},
        "subtitle":{type:String,default:"理科数学"},
        "attention":{type:String,default:"注意事项：\n1．答卷前，考生务必将自己的姓名、准考证号填写在答题卡上。 \n2．作答时，务必将答案写在答题卡上。写在本试卷及草稿纸上无效。 \n3．考试结束后，将本试卷和答题卡一并交回。"}
    },
    "front":{
        "part1":[{
            "title":{type:String,default:"一.选择题（12小题，每题5分，共60分，以下选项中只有一项正确"},
            "showEditor":{type:Boolean,default:false},
            "subjectType":{type:String,default:"choice"},
            "subjects":[
                {
                    "title":{type:String,default:"111111111111\\ce{CO2 + C -> 2 CO}1111111111111444^2"},
                    "testLayout":{type:String,default:"TB"},
                    "layout":{type:String,default:"align"},
                    "panelTopHeight":{type:Number,default:0},
                    "panelBottomHeight":{type:Number,default:128},
                    "panelRightWidth":{type:Number,default:0},
                    "showEditor":{type:Boolean,default:false},
                    "sectionLists":[
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        }
                    ]
                }              
            ]           
        }],
        "part2":[{
            "title":{type:String,default:"一.问答题（12小题，每题5分，共60分，以下选项中只有一项正确）"},
            "subjectType":{type:String,default:"topic"},
            "subjects":[
                {
                    "title":String,
                    "testLayout":{type:String,default:"TB"},
                    "layout":{type:String,default:"align"},
                    "panelTopHeight":{type:Number,default:0},
                    "panelBottomHeight":{type:Number,default:100},
                    "showEditor":{type:Boolean,default:false},
                    "panelRightWidth":{type:Number,default:0},
                    "sectionLists":[
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        }                                                                        
                    ]
                }               
            ]             
        }]
    },
    "back":{
        "part1":[{
            "title":{type:String,default:"一.选择题（12小题，每题5分，共60分，以下选项中只有一项正确"},
            "showEditor":{type:Boolean,default:false},
            "subjectType":{type:String,default:"choice"},
            "subjects":[
                {
                    "title":{type:String,default:"111111111111\\ce{CO2 + C -> 2 CO}1111111111111444^2"},
                    "testLayout":{type:String,default:"TB"},
                    "layout":{type:String,default:"align"},
                    "panelTopHeight":{type:Number,default:0},
                    "panelBottomHeight":{type:Number,default:128},
                    "panelRightWidth":{type:Number,default:0},
                    "showEditor":{type:Boolean,default:false},
                    "sectionLists":[
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        }
                    ]
                }              
            ]           
        }],
        "part2":[{
            "title":{type:String,default:"一.问答题（12小题，每题5分，共60分，以下选项中只有一项正确）"},
            "subjectType":{type:String,default:"topic"},
            "subjects":[
                {
                    "title":String,
                    "testLayout":{type:String,default:"TB"},
                    "layout":{type:String,default:"align"},
                    "panelTopHeight":{type:Number,default:0},
                    "panelBottomHeight":{type:Number,default:100},
                    "showEditor":{type:Boolean,default:false},
                    "panelRightWidth":{type:Number,default:0},
                    "sectionLists":[
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        },
                        {
                            "showEditor":{type:Boolean,default:false},
                            "text":String,
                            "img":[]
                        }                                                                        
                    ]
                }               
            ]             
        }]        
    }    
},{ collection: "testPaper"});

// 导出 testPapaer 模块
module.exports = mongoose.model('testPapaer', BookSchema);